# Generated by Django 5.1.2 on 2024-10-19 20:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_etiqueta_articulo_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='contenido',
            field=tinymce.models.HTMLField(default='Sin contenido'),
        ),
    ]
